### ISSUE TITLE
WinNMC: Unable to test the NCDNS part of the package.

### ISSUE THREAD

**Issue by jonasbits** [hlandau/ncdns#1]
namecoind works with namecoin-cli name_show,
Unbound works with 127.0.0.1

I can not confirm that "ncdns" works.

Tested with 64 bit win7.
C:\Program Files (x86)\
but found reference to C:\Program Files\

Could not resolve explorer.bit

**Comment by hlandau** [comment]
Please contact me on IRC and we'll troubleshoot this.
