### ISSUE TITLE
Cannot bind to port 53

### ISSUE THREAD

**Issue by yield65** [hlandau/ncdns#13]
Hi,
As per documentation I tried
sudo setcap 'cap_net_bind_service=+ep' ./ncdns
sudo setcap 'cap_net_bind_service=+ep' /home/myusername/goprojects/bin/ncdns

sudo /home/yield/goprojects/bin/ncdns -uid nobody 
Although this I suppose it's now -service.uid
sudo /home/yield/goprojects/bin/ncdns -service.uid nobody
sudo /home/yield/goprojects/bin/ncdns -service.uid myusername

And all of them resulted in
20161111211817 [CRITICAL] ncdns.server: fatal: : listen tcp :53: bind: permission denied

Right now I'm binding it on :5454 and using ufw to make the port forward from :53 to :5454 but I don't think this is the intended use.
I'm on ubuntu 16.10 kernel 4.4.0-45-generic, ncdns compiled from git repo.
Thanks.

**Comment by hlandau** [comment]
Fixed.
