### ISSUE TITLE
Is root needed or not?

### ISSUE THREAD

**Issue by dionyziz** [hlandau/ncdns#5]
The default port for ncdns is port 53. However, if ncdns is run as non-root, it is not able to bind port 53 due to privilege issues. On the other hand, if it is run as root, it refuses to run.

Let's fix this and allow it to drop privileges like most daemons do nowadays.

**Comment by hlandau** [comment]
Err, it supports dropping privileges. Maybe this needs to be better documented.

You can run it on another port as non-root, which is the sane thing to do if you want to use it with Unbound.
Or you can run it as root and drop privileges by passing `--service.uid=UID --service.daemon=`.

**Comment by dionyziz** [comment]
How can we better document this capability?
